import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  transpilePackages: [
    "antd",
    "@ant-design/icons",
    "@ant-design/cssinjs",
    "@ant-design/nextjs-registry",
    "rc-util",
    "rc-pagination",
    "rc-picker",
    "rc-tree",
    "rc-table",
    "rc-input",
    "rc-select",
    "rc-cascader",
    "rc-checkbox",
    "rc-dropdown",
    "rc-menu",
    "rc-motion",
    "rc-tooltip",
    "rc-drawer",
    "rc-dialog",
    "rc-notification",
    "rc-textarea",
    "rc-resize-observer",
    "rc-collapse",
    "rc-overflow",
    "rc-segmented",
    "rc-image",
    "rc-slider",
    "rc-switch",
    "rc-tabs",
    "rc-upload",
    "rc-virtual-list",
    "rc-field-form",
    "rc-form",
    "rc-progress",
    "rc-rate",
    "rc-steps",
    "rc-mentions",
  ],
};

export default nextConfig;